	# This is a makefile.
	# Lukus Hendrix 
	# Z1761354

z1761354_A3 : z1761354_A3.o 
	g++ -Wall -o z1761354_A3 z1761354_A3.o 

	
z1761354_A3.o : z1761354_A3.cpp 
	g++ -Wall -c z1761354_A3.cpp      

	
	# Clean is an example of a pseudo-target.
	# We use it to clean up the working directory.

clean :
	- rm *.o z1761354_A3
