	# This is a makefile.
	# Lukus Hendrix 
	# Z1761354

Assign2 : Assign2.o 
	g++ -Wall -o Assign2 Assign2.o 

	
Assign2.o : Assign2.cpp 
	g++ -Wall -c Assign2.cpp      

	
	# Clean is an example of a pseudo-target.
	# We use it to clean up the working directory.

clean :
	- rm *.o Assign2
